### ISSUE TITLE
IEEEmadC 

### ISSUE THREAD

**Issue by SangramChavan** [HabibRh26/IEEE-madC-app-Medicine-Reminder-#1]
Your repo is missing a lot of info 

Kindly use below template to create your Readme.md file 
Update following info and then submit the app on IEEEmadC-wiki page

<p align="center">
  <a href="https://github.com/{add repo link}]">
    <img src="{add graphic poster}" alt="{App Name}" width=180 height=150>
  </a>
  <h3 align="center">{Enter App Name}</h3>
</p>
<p align="center">
    <h4>{Enter App short discription in one line.}<br></h4>
</p>
<p>
   <h5>{Enter discription about what it does.} <br></h5>
   <h5>{more info..}<br></h5>
</p>
## Table of contents
- [About the Project](#)
- [General Preview](#)
- [Technical](#)
    - [Project Dependencies](#)
- [To Do List](#)
- [Permissions](#)
- [Versions](#)
- [Contact Information](#)
- [{app name}]({add repo link})
### about {Enter App name}
{What can you do with the app?}
### GENERAL PREVIEW 
![3images](https://github.com/JobGetabu/Darasa-IEEEMadC/blob/master/screenshots/lec_screens.png)
### GENERAL PREVIEW of APP
![3images]({Add startup screen image here})
### about Web dashboard {add if applicable else remove this section}
{One line and screenshot about the dashboad if applies to your app}
### GENERAL PREVIEW WEB Version {add if applicable else remove this section}
<img src="{link of screenshot}">
#### App preview 1                                                
<img src="https://github.com/JobGetabu/Darasa-IEEEMadC/blob/master/screenshots/LecAppVideo.gif" width="300">
#### App preview 2
<img src="https://github.com/JobGetabu/Darasa-IEEEMadC/blob/master/screenshots/StudAppVideo.gif" width="300">
##### App is now available: {add if applicable else remove this section}
![WithExplanations](https://github.com/JobGetabu/Darasa-IEEEMadC/blob/master/screenshots/DARASA%20BANNER%20EDIT.png)
#### App Store
[![Download it on Google Play](https://raw.githubusercontent.com/tamzi/ReadMe-MasterTemplates/master/android/images/gplay.png)](https://play.google.com/store/apps/details?id=com.job.darasastudent)
## Permissions
1. Internet
2. Network state
3. Location 
## To Do List {add if applicable else remove this section}
Add the various things that you are working on.  
- [x] Creating a Qr code for app
- [ ] Updating the App to use AndroidX
### Promo Video (Click for full video)
[![Watch the video]({add .gif if exist})]({your youtube video link here})
### Assets and Credits
* Credit to artists [images,gifs...]({Links})
* [{Library name}]({link})
### Team Contributored
* [{Enter name}]({Enter link to profile if applicable})
### Want to contribute? {add if you wish to accept people to contribute to this app else remove this section}
I would/ We'd love to have your help in making  **{Enter app name}** better. The project is still very incomplete, but if there's an issue you'd like to see addressed sooner rather than later, let me(/us) know. 
For any concerns, please open an [issue](https://github.com/{usernmae}/{repo name}/issues), or JUST, [fork the project and send a pull request](https://github.com/{username}/{repo name}/pulls). 
## License 
* see [LICENSE](https://github.com/{username}/{reponame}/blob/master/LICENSE) file
### Lecturer app
* Version 2.0  DATE 2/12/2018
* [Download {App name}]({add link if you have published in play store else remore this section})
## Contact information 
For personal feedback or questions feel free to contact me via the mail address, which is mentioned on my [Github profile](https://github.com/{username}). If you have found any bugs or want to post a feature request please use the [bugtracker](https://github.com/{username}/{repo name}/issues) to report them.
#### Developers {add if applicable else remove this section}
* Homepage: 
[@About Me]({Enter your website})
* Twitter: 
[{Twitter username}]({Twitter link})
### Summary
| [{Enter app name}]({add link to executable file}) | Team Name: {Enter Team name}({add link of your repo here}) | {add one line discripiton} | [LICENSE]({link to licence}) | {Enter your country name} | [{team member 1}](https://github.com/{username}) | [{team member 2}](https://github.com/{user name}) | [{team member 3}](https://github.com/{username})
[![Open Source Love](https://badges.frapsoft.com/os/v2/open-source-200x33.png?v=103)](https://github.com/ellerbrock/open-source-badge/)

**Comment by HabibRh26** [comment]
Do my submission ok or still has issues?

**Comment by SangramChavan** [comment]
Summary missing

### Summary | [{Enter app name}]({add link to executable file}) | Team Name: {Enter Team name}({add link of your repo here}) | {add one line discripiton} | [LICENSE]({link to licence}) | {Enter your country name} | [{team member 1}](https://github.com/{username}) | [{team member 2}](https://github.com/{user name}) | [{team member 3}](https://github.com/{username})

**Comment by HabibRh26** [comment]
Summary |
 [{Medicare}]({https://github.com/HabibRh26/IEEE-madC-app-Medicine-Reminder-/tree/master/apk})
Team Name: {juphoneix_girls}({https://github.com/HabibRh26/IEEE-madC-app-Medicine-Reminder-}) | {Medication App} | [LICENSE]({https://github.com/HabibRh26/IEEE-madC-app-Medicine-Reminder-/pull/2/commits/d41956fa1e3c6c955e0c4fb46bf0915ae91d4ca8}) | {Bangladesh} |
 {Md.Habibur Rahman}(https://github.com/HabibRh26/IEEE-madC-app-Medicine-Reminder-) 
[{Tabia Tanzin Prema}] | {Md.Mushfique Anwar}
